name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Install golangci-lint
      run: |
        go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
        sudo mv $(go env GOPATH)/bin/golangci-lint /usr/local/bin/

    - name: Run Linter
      run: golangci-lint run --verbose ./...

    - name: Build
      run: go build .
